vars

diff --git a/.github/workflows/daily-automatic-update.yml b/.github/workflows/daily-automatic-update.yml
--- a/.github/workflows/daily-automatic-update.yml
+++ b/.github/workflows/daily-automatic-update.yml
@@ -9,7 +9,7 @@ env:
   TOKEN: ${{ secrets.TOKEN }}
   NAME: ${{ secrets.NAME }}
   EMAIL: ${{ secrets.EMAIL }}
-  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
+  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
 
 jobs:
 
@@ -22,15 +22,33 @@ jobs:
       - name: Setting up build version
         run: |
           version=$(($GITHUB_RUN_NUMBER))
-          echo "BUILD_VERSION=2.2.$version" >> ${GITHUB_ENV}
+          echo "BUILD_VERSION=3.0.$version" >> ${GITHUB_ENV}
 
       - name: Setup .NET
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: 9.0.x
 
-      - name: Install dependencies
-        run: dotnet restore
+      - name: Install dependencies with retry
+        run: |
+          retries=5
+          base_wait_time=15
+          exponent=2
+
+          for i in $(seq 1 $retries); do
+            if dotnet restore; then
+              break
+            fi
+
+            if [ $i -lt $retries ]; then
+              wait_time=$(awk "BEGIN {print int($base_wait_time * ($exponent ^ ($i - 1)))}")
+              echo "dotnet restore failed, retrying in $wait_time seconds..."
+              sleep $wait_time
+            else
+              echo "dotnet restore failed after $retries retries."
+              exit 1
+            fi
+          done
 
       - name: Build
         run: dotnet build --configuration Release --no-restore
